version: 2
updates:
- package-ecosystem: npm
  directory: "/samples"
  schedule:
    interval: daily
    time: "05:00"
    timezone: "America/Los_Angeles"
  labels:
  - dependencies
  versioning-strategy: auto
  commit-message:
    prefix: ðŸ“¦
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: daily
    time: "05:00"
    timezone: "America/Los_Angeles"
  labels:
  - dependencies
  versioning-strategy: auto
  commit-message:
    prefix: ðŸ“¦
  open-pull-requests-limit: 10