name: CalculatorCoreAppNuGet CI

on:
  schedule:
    - cron: '0 15 * * 2' # Tuesday 3PM UTC (8AM PST)
  push:
    branches:
      - main
    paths:
      - 'samples/CalculatorCoreAppNuGet/**'
      - '.github/workflows/samples-CalculatorCoreAppNuGet-ci.yml'

jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        sample: [CalculatorCoreAppNuGet]
        architecture: [x86, x64, ARM64]
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment info
        run: npx envinfo

      - name: Relocate to reduce long paths
        run:  Copy-item -Force -Recurse -Verbose "samples\${{ matrix.sample }}" -Destination "..\..\src"

      - name: Get starting folder size
        run: ${{github.workspace}}\.github\scripts\GetFolderSize.ps1
        working-directory: ..\..\src

      - name: Yarn install
        run: yarn install --frozen-lockfile
        working-directory: ..\..\src

      - name: Decode the pfx
        run: |
          $PfxBytes = [System.Convert]::FromBase64String("${{ secrets.SAMPLES_BASE64_ENCODED_PFX }}")
          $PfxPath = [System.IO.Path]::GetFullPath("${{github.workspace}}\GitHubActionsWorkflow.pfx")
          Write-Host $PfxPath
          [System.IO.File]::WriteAllBytes("$PfxPath", $PfxBytes)
        working-directory: ..\..\src

      - name: Run react-native run-windows
        run: npx react-native run-windows --logging --no-packager --no-launch --arch ${{ matrix.architecture }} ${{ startsWith(matrix.architecture, 'ARM') && '--no-deploy' || '' }} ${{ matrix.configuration == 'Release' && '--release' || '' }} --msbuildprops PackageCertificateKeyFile=${{github.workspace}}\GitHubActionsWorkflow.pfx
        working-directory: ..\..\src

      - name: Remove the pfx
        run: |
          $certificatePath = [System.IO.Path]::GetFullPath("${{github.workspace}}\GitHubActionsWorkflow.pfx")
          Write-Host $certificatePath
          Remove-Item -path $certificatePath
        working-directory: ..\..\src

      - name: Get final folder size
        run: ${{github.workspace}}\.github\scripts\GetFolderSize.ps1
        working-directory: ..\..\src

