name: CameraDemo CI (Upgrade)

on:
  schedule:
    - cron: '0 15 * * 2' # Tuesday 3PM UTC (8AM PST)
  push:
    branches:
      - main
    paths:
      - '.github/workflows/samples-CameraDemo-ci-upgrade.yml'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sample: [CameraDemo]
        architecture: [x86, x64, ARM64]
        configuration: [Debug, Release]
        reactNativeWindowsVersion: [latest, preview, canary]
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment info
        run: npx envinfo

      - name: Relocate to reduce long paths
        run:  Copy-item -Force -Recurse -Verbose "samples\${{ matrix.sample }}" -Destination "..\..\src"

      - name: Yarn install
        run: yarn install
        working-directory: ..\..\src

      - name: Upgrade react-native-windows
        id: upgrade
        continue-on-error: true
        run: ${{github.workspace}}\.github\scripts\UpgradeSmokeTest.ps1 ${{ matrix.reactNativeWindowsVersion }} -Force ${{ format('${0}', contains(matrix.reactNativeWindowsVersion, 'canary')) }}
        working-directory: ..\..\src

      - name: Run react-native-windows-init
        if: ${{ steps.upgrade.outcome == 'success' }}
        run: npx react-native-windows-init --overwrite --version ${{ matrix.reactNativeWindowsVersion }}
        working-directory: ..\..\src

      - name: Run react-native run-windows
        if: ${{ steps.upgrade.outcome == 'success' }}
        run: npx react-native run-windows --logging --no-packager --no-launch --deploy-from-layout --arch ${{ matrix.architecture }} ${{ startsWith(matrix.architecture, 'ARM') && '--no-deploy' || '' }} ${{ matrix.configuration == 'Release' && '--release' || '' }}
        working-directory: ..\..\src
