name: CameraDemo CI

on:
  schedule:
    - cron: '0 15 * * 2' # Tuesday 3PM UTC (8AM PST)
  push:
    branches:
      - main
    paths:
      - 'samples/CameraDemo/**'
      - '.github/workflows/samples-CameraDemo-ci.yml'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sample: [CameraDemo]
        architecture: [x86, x64, ARM64]
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment info
        run: npx envinfo

      - name: Relocate to reduce long paths
        run:  Copy-item -Force -Recurse -Verbose "samples\${{ matrix.sample }}" -Destination "..\..\src"

      - name: Get starting folder size
        run: ${{github.workspace}}\.github\scripts\GetFolderSize.ps1
        working-directory: ..\..\src

      - name: Yarn install
        run: yarn install --frozen-lockfile
        working-directory: ..\..\src

      - name: Run react-native run-windows
        run: npx react-native run-windows --logging --no-packager --no-launch --deploy-from-layout --arch ${{ matrix.architecture }} ${{ startsWith(matrix.architecture, 'ARM') && '--no-deploy' || '' }} ${{ matrix.configuration == 'Release' && '--release' || '' }}
        working-directory: ..\..\src

      - name: Get final folder size
        run: ${{github.workspace}}\.github\scripts\GetFolderSize.ps1
        working-directory: ..\..\src

