name: Weekly CI

on:
  schedule:
    - cron: '0 15 * * 2' # 3PM Tuesday UTC (8AM Tuesday PST)
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/samples-weekly-CI.yml'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/samples-weekly-CI.yml'

jobs:
  build:
    name: CI Build
    runs-on: windows-latest
    strategy:
      matrix:
        sample: [Calculator, NativeModuleSample\cppwinrt, NativeModuleSample\csharp]
        architecture: [x86, x64]
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v2

      - name: Relocate to reduce long paths
        run:  Copy-item -Force -Recurse -Verbose "samples\${{ matrix.sample }}" -Destination "..\..\src"

      - name: Yarn install
        run: yarn install
        working-directory: ..\..\src

      - name: Build ${{ matrix.architecture }} Debug
        if: ${{ matrix.configuration == 'Debug' }}
        run: npx react-native run-windows --no-launch --no-packager --logging --arch ${{ matrix.architecture }}
        working-directory: ..\..\src

      - name: Build ${{ matrix.architecture }} Release
        if: ${{ matrix.configuration == 'Release' }}
        run: npx react-native run-windows --no-launch --no-packager --logging --release --arch ${{ matrix.architecture }}
        working-directory: ..\..\src
