name: NativeModuleSample CI (Upgrade)

on:
  schedule:
    - cron: '0 15 * * 2' # Tuesday 3PM UTC (8AM PST)
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/samples-NativeModuleSample-ci-upgrade.yml'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        sample: [NativeModuleSample\cppwinrt, NativeModuleSample\csharp]
        architecture: [x86, x64, ARM, ARM64]
        configuration: [Debug, Release]
        reactNativeWindowsVersion: [latest, preview, canary]
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment info
        run: npx envinfo

      - name: Relocate to reduce long paths
        run:  Copy-item -Force -Recurse -Verbose "samples\${{ matrix.sample }}" -Destination "..\..\src"

      - name: Yarn install
        run: yarn install
        working-directory: ..\..\src

      - name: Upgrade react-native-windows
        id: upgrade
        continue-on-error: true
        run: ${{github.workspace}}\.github\scripts\UpgradeSmokeTest.ps1 ${{ matrix.reactNativeWindowsVersion }} -Force ${{ format('${0}', contains(matrix.reactNativeWindowsVersion, 'canary')) }}
        working-directory: ..\..\src

      - name: Build ${{ matrix.architecture }} Debug
        if: ${{ steps.upgrade.outcome == 'success' && matrix.configuration == 'Debug' }}
        run: npx react-native run-windows --no-deploy --no-launch --no-packager --no-autolink --logging --arch ${{ matrix.architecture }}
        working-directory: ..\..\src

      - name: Build ${{ matrix.architecture }} Release
        if: ${{ steps.upgrade.outcome == 'success' && matrix.configuration == 'Release' }}
        run: npx react-native run-windows --no-deploy --no-launch --no-packager --no-autolink --logging --release --arch ${{ matrix.architecture }}
        working-directory: ..\..\src
