name: CameraDemo PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'samples/CameraDemo/**'
      - '.github/workflows/samples-CameraDemo-pr.yml'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment info
        run: npx envinfo

      - name: Relocate to reduce long paths
        run:  Copy-item -Force -Recurse -Verbose "samples\CameraDemo" -Destination "..\..\src"

      - name: Yarn install
        run: yarn install --frozen-lockfile
        working-directory: ..\..\src

      - name: Build x86 Debug
        run: npx react-native run-windows --no-launch --deploy-from-layout --no-packager --logging
        working-directory: ..\..\src
