name: Calculator PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'samples/Calculator/**'
      - '.github/workflows/samples-Calculator-pr.yml'

jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      matrix:
        language: [cppwinrt, csharp]
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment info
        run: npx envinfo

      - name: Relocate to reduce long paths
        run:  Copy-item -Force -Recurse -Verbose "samples\Calculator\${{ matrix.language }}" -Destination "..\..\src"

      - name: Yarn install
        run: yarn install --frozen-lockfile
        working-directory: ..\..\src

      - name: Build x86 Debug
        run: npx react-native run-windows --no-launch --no-packager --logging
        working-directory: ..\..\src

  prcheck:
    name: Successful PR Check
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - uses: actions/checkout@v3
