name: RNW Website PR

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/website-ci.yml'
      - '.github/workflows/website-pr.yml'
      - 'docs/**'
      - 'website/**'

defaults:
  run:
    shell: pwsh

jobs:
  website_pr:
    name: Website PR
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Spell-check docs
      run: npx markdown-spellcheck "docs/*.md" "!docs/*-api-windows.md" --en-us --ignore-acronyms --ignore-numbers --report --color

    - name: Check unbroken exclusions file
      run: ${{github.workspace}}/.github/scripts/CheckUnbrokenExclusions.ps1

    - name: Check for Broken Links (Docs)
      run: npx unbroken --parse-ids
      working-directory: ./docs

    - name: Check for Broken Links (Website)
      if: success() || failure()
      run: npx unbroken --parse-ids
      working-directory: ./website

    - name: Yarn Install (Website)
      if: success() || failure()
      run: yarn install --frozen-lockfile
      working-directory: ./website

    - name: Yarn Build (Website)
      run: yarn build
      working-directory: ./website
  
  prcheck:
    name: Successful PR Check
    runs-on: ubuntu-latest
    needs: [website_pr]
    steps:
     - uses: actions/checkout@v3
